### ISSUE TITLE
Update Dates and Times FORMAT in Master data templates

### ISSUE THREAD

**Issue by wuritechteam** [WuriGuinea/mosip-guinea-ref-impl#116]
In  the Master data template, we have place holders for date and time in sevral places in. Hoever the output is the English Format. 

Please change in FRENCH format. 

Date Format = JJ/MM/YYYY 
Time Format = hh:mm (24h format). Ex: 10:05 PM => 22:05 

EX. OTP EMAIL :

![image](https://user-images.githubusercontent.com/64075677/90791968-6bb54f80-e2f9-11ea-9c0a-8f9e10996731.png)

**Comment by tisshadjac** [comment]
resolved
