### ISSUE TITLE
Variables not updating in notification emails

### ISSUE THREAD

**Issue by tisshadjac** [WuriGuinea/mosip-guinea-ref-impl#159]
OTP email is showing $validTime variable name instead of the associated value 
![image](https://user-images.githubusercontent.com/64141579/91922423-9a391000-ec93-11ea-9319-8b318229de78.png)

![image](https://user-images.githubusercontent.com/64141579/92476086-08099e00-f1a4-11ea-9d76-291851ce4e66.png)

**Comment by hosurkrishnan** [comment]
Request this be taken by the Guinea team.    We will explain what needs to be done.

**Comment by wuritechteam** [comment]
The Wuri team is not considering it as a priority in the pilot phase
