### ISSUE TITLE
Additional address details-i.e. "complément d'adresse" not populated in notification email and/or INU card

### ISSUE THREAD

**Issue by tisshadjac** [WuriGuinea/mosip-guinea-ref-impl#198]
See Row 1131 in Master templates,  
$!additionalAddressDetails_fra

**Comment by wuritechteam** [comment]
@ankitvaishnav to provide ETA

**Comment by ankitvaishnav** [comment]
ETA - 12 Oct

**Comment by wuritechteam** [comment]
@ankitvaishnav to debug today

**Comment by ankitvaishnav** [comment]
Current status: debugging

**Comment by ankitvaishnav** [comment]
For UIN card fix: PR created

**Comment by wuritechteam** [comment]
Mouctar to update Master template DB today.
@Goumou7 to test and close

**Comment by ankitvaishnav** [comment]
Use additionalAddressDetails, dont append the language in templates

**Comment by wuritechteam** [comment]
Mouctar to update Master template DB today.
@Goumou7 to test and close

**Comment by wuritechteam** [comment]
@Goumou7 the DB is up to date now. Please sync your local DB and Test

**Comment by tisshadjac** [comment]
@Goumou7 pending test. ETA 10/20

**Comment by wuritechteam** [comment]
[](url)
[1.pdf](https://github.com/WuriGuinea/mosip-guinea-ref-impl/files/5403329/1.pdf)
[2.pdf](https://github.com/WuriGuinea/mosip-guinea-ref-impl/files/5403333/2.pdf)

**Comment by wuritechteam** [comment]
Tested and all good
