### ISSUE TITLE
Correction to notification emails

### ISSUE THREAD

**Issue by tisshadjac** [WuriGuinea/mosip-guinea-ref-impl#199]
![image](https://user-images.githubusercontent.com/64141579/92719442-bf2f2200-f328-11ea-846e-2ba8caa751aa.png)
![image](https://user-images.githubusercontent.com/64141579/92719486-ce15d480-f328-11ea-8fec-6797ab2e1f5b.png)

+**Acceptance criteria**+

“UIN Generated” email notification subject line should read “Traitement de la demande INU complet”

“MOSIP REGISTRATION NOTIFICATION” email notification subject line should read “UNIR - Notification de l'enregistrement”

**Comment by wuritechteam** [comment]
@tisshadjac confrimed the bug is fixed.
