### ISSUE TITLE
Reg Processor build error

### ISSUE THREAD

**Issue by wuritechteam** [WuriGuinea/mosip-guinea-ref-impl#228]
![image](https://user-images.githubusercontent.com/64075677/93509626-8508e600-f90f-11ea-851c-6bc8f2153dcb.png)

**Comment by wuritechteam** [comment]
Krish to investigate and fix

**Comment by wuritechteam** [comment]
@ankitvaishnav  to raise a PR today , ETA = Oct 05

**Comment by wuritechteam** [comment]
@ankitvaishnav to raise PR today targeting **DEV**

**Comment by tisshadjac** [comment]
pending verification with @wuritechteam
