### ISSUE TITLE
Receiving notification from Guinean SMS Provider

### ISSUE THREAD

**Issue by condeis** [WuriGuinea/mosip-guinea-ref-impl#235]
currently test messages are received on the defined number, but no effective OTP notification (client reg, prereg ...)

**Comment by wuritechteam** [comment]
@ankitvaishnav and @condeis to check if sms provider impl. had been deployed. 
ETA = ? (Ankit will provide)

**Comment by wuritechteam** [comment]
@ankitvaishnav to update ETA

**Comment by ankitvaishnav** [comment]
Still debugging. Added more logs in notification service for debugging

**Comment by ankitvaishnav** [comment]
deployed

**Comment by wuritechteam** [comment]
SMS are now received.
@condeis to check with @ankitvaishnav for datetime format issue

**Comment by wuritechteam** [comment]
Fixed. @condeis to open new issue for date time formatting
