### ISSUE TITLE
In Acknowledgement page display issue 

### ISSUE THREAD

**Issue by wuritechteam** [WuriGuinea/mosip-guinea-ref-impl#247]
@ankitvaishnav  @wuritechteam  @tisshadjac In aknowledgement page, header and photo are diplay on front of the page, and all others resident information are diplay on the back of the page.
[10001910030003620200924114704_Ack.pdf](https://github.com/WuriGuinea/mosip-guinea-ref-impl/files/5370795/10001910030003620200924114704_Ack.pdf)

**Comment by wuritechteam** [comment]
MOUCTAR TO APPLY pending changes in master template DB today

**Comment by wuritechteam** [comment]
@tisshadjac to test with @Goumou7 and close

**Comment by tisshadjac** [comment]
follow up today @tisshadjac @Goumou7

**Comment by wuritechteam** [comment]
Verified
