### ISSUE TITLE
Add Reminder Module Deployment Scripts

### ISSUE THREAD

**Issue by mombe090** [WuriGuinea/mosip-guinea-ref-impl#274]

**Comment by wuritechteam** [comment]
@ankitvaishnav and @mombe090 to finalize deployment today

**Comment by wuritechteam** [comment]
@mombe090  and @condeis , ETA = Nov. 10

**Comment by mombe090** [comment]
As discuss with @condeis, the deployment reminder is under batchjob module, so we can close this ticket
