### ISSUE TITLE
Synchorization issue with the local DB

### ISSUE THREAD

**Issue by wuritechteam** [WuriGuinea/mosip-guinea-ref-impl#275]
After syncing the data in the local db is not update automatically, even after showing successful sync sometime it doesn't give acess to new registration
![image](https://user-images.githubusercontent.com/64075677/97894702-b9ebc380-1d2a-11eb-8ff7-2f420211ab72.png)

**Comment by wuritechteam** [comment]
@ankitvaishnav and @Goumou7 to fix it Thursday 05.

**Comment by wuritechteam** [comment]
@Goumou7 and @ankitvaishnav , ETA = Nov. 11

**Comment by ankitvaishnav** [comment]
Please use guinea-sandbox.mosip.net for testing

**Comment by wuritechteam** [comment]
ETA = Nov. 12

**Comment by wuritechteam** [comment]
tested and fixed, by targeting AWS
