### ISSUE TITLE
[Info] keymanager key generation

### ISSUE THREAD

**Issue by ankitvaishnav** [WuriGuinea/mosip-guinea-ref-impl#282]
Possible Errors:

- No unique alias is found

Resolution:

1. Go inside the keymanager pod docker
2. Download PKXS11Test.java java program in the keyManager Docker ([PKXS11Test.java](https://public-ank.s3-us-west-2.amazonaws.com/PKCS11Test.java)).
3. download thebouncycastle  jar file directly inside docker [bouncycastle](https://www.bouncycastle.org/download/bcprov-jdk14-166.jar)
4. Run command javac -classpath bcprov-jdk*.jar PKCS11Test.java
5. Run command java -cp bcprov-jdk*.jar:.: PKCS11Test - this will create new key pair in SoftHSM docker. and prints new Key UUID on the console.. Copy the new UUID in a text file.
6. Update the New UUID in DB table (mosip_kernel.key_alias) where AppID is KERNEL & RefID is SIGN and update the generation time to current time & expiry time to one year from current time.
7. Restart the keyManager Docker.

**Comment by wuritechteam** [comment]
@mombe090  to document and close. ETA = NOv. 12

**Comment by mombe090** [comment]
Documentation done and is ready on shared drive https://drive.google.com/file/d/1qyzdWAMcTmf8qZdx2kCIn0lrolIBM7I7/view?usp=sharing
