### ISSUE TITLE
[Info] Renew letsencrypt SSL certificate

### ISSUE THREAD

**Issue by ankitvaishnav** [WuriGuinea/mosip-guinea-ref-impl#283]
Follow the steps on server:

- Go to home folder
- Run command `sudo .venv-py3/bin/certbot certonly --nginx`

**Comment by wuritechteam** [comment]
Yaya to automate the process. ETA = today

**Comment by wuritechteam** [comment]
Yaya to automate the process. ETA = today

**Comment by wuritechteam** [comment]
Yaya to automate the process. ETA = Fri, 27th

**Comment by wuritechteam** [comment]
Yaya to automate the process. ETA = Fri, 27th

**Comment by mombe090** [comment]
Done
