### ISSUE TITLE
Acknowledgement template 2 throws error in registration client preview page

### ISSUE THREAD

**Issue by ankitvaishnav** [WuriGuinea/mosip-guinea-ref-impl#284]
Resolution:

[template_ack_2.txt](https://github.com/WuriGuinea/mosip-guinea-ref-impl/files/5523256/template_ack_2.txt)

**Comment by wuritechteam** [comment]
Mouctar to update Master data csv

**Comment by wuritechteam** [comment]
ID: 1139
Name : reg-ack-template-part2

**Comment by wuritechteam** [comment]
@ankitvaishnav to run db script today

**Comment by wuritechteam** [comment]
@ankitvaishnav to run the DB script today. + @mombe090

**Comment by wuritechteam** [comment]
@Goumou7  to test and close today

**Comment by wuritechteam** [comment]
Verified resolved
