### ISSUE TITLE
Failure to synchronise DB Schema from a new RegClient

### ISSUE THREAD

**Issue by tisshadjac** [WuriGuinea/mosip-guinea-ref-impl#388]

**Comment by tisshadjac** [comment]
Not recognizing devices when onboarding new operator onward after replacing the db 

@condeis @Goumou7  @mombe090 to confirm that devices are registered in db 

eta today (12/14)

**Comment by condeis** [comment]
@tisshadjac @Goumou7 issue corrected, it was related to master data (key index into master_machine)

**Comment by wuritechteam** [comment]
Verified and tested
