### ISSUE TITLE
KERNEL key SIGNING are anterior to current date

### ISSUE THREAD

**Issue by tisshadjac** [WuriGuinea/mosip-guinea-ref-impl#391]
certificates issued are past dated

 will document ticket

related to older docker image in github repo per  

  will send full docker image name

Assign Logar/Ankit

scope ? (i.e. modules impacted)

**Comment by tisshadjac** [comment]
@mombe090 @ankitvaishnav  working on creating a patch

**Comment by tisshadjac** [comment]
Yaya to follow up 
eta is 12/16

**Comment by wuritechteam** [comment]
@mombe090 to document the (manual) solution. 
ETA = 15 Jan. 2021

**Comment by wuritechteam** [comment]
Mouctar to review doc today

**Comment by mombe090** [comment]
@wuritechteam please see the link https://wuriguineecom.sharepoint.com/:b:/s/WURIGUINEE/EQnhBU-rai1EvFENAInGM_YB9GOi-p9cUoHqJE1MvUiSNg?e=4JTutm
