### ISSUE TITLE
API center creation 500 duplicate 

### ISSUE THREAD

**Issue by mombe090** [WuriGuinea/mosip-guinea-ref-impl#428]
Hey @ankitvaishnav, please as discuss this issue for error duplication found when we try to create a new center
![image](https://user-images.githubusercontent.com/14869997/111991139-e05ca080-8b0b-11eb-8980-858ffbde98f3.png)

**Comment by mombe090** [comment]
{
    "id":"",
    "metadata":{
    },
    "request":{
      "addressLine1":"Test FROM API 1",
      "addressLine2":"CONAKRY",
      "addressLine3":"GUINEE",
      "centerEndTime":"18:30:00",
      "centerStartTime":"08:00:00",
      "centerTypeCode":"CEI",
      "contactPerson":"Tech Team",
      "contactPhone":"62220000",
      "exceptionalHolidayPutPostDto":[],
      "holidayLocationCode":"GN",
      "id":"",
      "isActive":true,
      "langCode":"fra",
      "latitude":"0.0000",
      "locationCode":"0040205",
      "longitude":"0.0000",
      "lunchEndTime":"14:00:00",
      "lunchStartTime":"13:00:00",
      "name":"Test Center API",
      "perKioskProcessTime":"00:15:00",
      "timeZone":"(GMT+00h00) GREENWICH MEAN TIME",
      "workingHours":"8",
      "workingNonWorkingDays":{
        "fri":true,
        "mon":true,
        "sat":false,
        "sun":false,
        "thu":true,
        "tue":true,
        "wed":true
      },
      "zoneCode":"1"
    },
    "requesttime":"2018-12-10T06:12:52.994Z",
    "version":"1.0"
  }

**Comment by ankitvaishnav** [comment]
Resolution: We have to update the rcid_seq with the last registration center id as we are inserting the data directly from the dmls.

Steps:

1. Connect with mosip_master database
2. Run query: `Insert into rcid_seq (curr_seq_no, cr_by, cr_dtimes, upd_by, upd_dtimes)
select max(id)::int, 'superadmin', now(), 'superadmin', now() from registration_center;`

**Comment by ankitvaishnav** [comment]
@mombe090 Please try and confirm

**Comment by mombe090** [comment]
hey @ankitvaishnav still not working 
{
  "id": "",
  "version": "1.0",
  "responsetime": "2021-03-23T12:19:42.909Z",
  "metadata": null,
  "response": null,
  "errors": [
    {
      "errorCode": "KER-MSD-060",
      "message": "Error occurred while Inserting Registration Center details  ERROR: duplicate key value violates unique constraint \"pk_regcntr_code\"\n  Detail: Key (id, lang_code)=(10001, fra) already exists."
    }
  ]
}

**Comment by mombe090** [comment]
Thanks @ankitvaishnav with the script u share, it's work fine now
Insert into rcid_seq (curr_seq_no, cr_by, cr_dtimes, upd_by, upd_dtimes) select max(id)::int, 'superadmin', now(), 'superadmin', now() from registration_center;
